### ISSUE TITLE
Build is failing with recent GHC releases

### ISSUE THREAD

**Issue by cbruegg** [brownsys/nettle-openflow#1]
Hi,

I'm a student research assistant at the University of Paderborn in Germany, trying to set up PANE for a research project. Unfortunately, I get the following error when trying to build `nettle-openflow`:

```
src/Nettle/OpenFlow/StrictPut.hs:51:10:
    No instance for (Applicative PutM)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Monad PutM’
```

I'm not familiar with Haskell, so it would be great if you could help us fix this. I've tried getting older versions of GHC to work, but that causes other difficulties.

Thanks for your help!

**Comment by arjunguha** [comment]
Unfortunately, this project is no longer maintained and recent versions of GHC have a habit of breaking old code. I suggest either:

1. Use the PANE VM, which should "just work" http://pane.cs.brown.edu or
2. Downgrade to an older version of GHC from around the time PANE was released.
